openapi: 3.0.2
info:
  contact:
    url: https://github.com/moov-io/paygate
  description: Paygate is a RESTful API enabling Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House))
    transactions to be submitted and received without a deep understanding of a full
    NACHA file specification.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Paygate Admin API
  version: v1
servers:
- description: Local development
  url: http://localhost:9092
tags:
- description: PayGate endpoints which are only meant to be exposed for admin dashboards
    and operations.
  name: Admin
paths:
  /version:
    get:
      operationId: getVersion
      responses:
        200:
          content:
            text/plain:
              schema:
                example: v0.7.1
                type: string
          description: The current version running
      summary: Show the current version
      tags:
      - Admin
  /features:
    get:
      operationId: getFeatures
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Features'
          description: A JSON object containing features and their status
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Get an object of enabled features for this PayGate instance
      tags:
      - Admin
  /configs/filetransfers:
    get:
      operationId: getConfigs
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configs'
          description: A JSON object containing ACH file transfer configurations
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Get current set of ACH file transfer configuration
      tags:
      - Admin
  /configs/filetransfers/{routingNumber}:
    delete:
      operationId: deleteFileTransferConfig
      parameters:
      - description: Routing Number
        explode: false
        in: path
        name: routingNumber
        required: true
        schema:
          example: "987654320"
          type: string
        style: simple
      responses:
        200:
          description: Removed file transfer config
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Remove a file transfer config for a given routing number
      tags:
      - Admin
    put:
      operationId: updateFileTransferConfig
      parameters:
      - description: Routing Number
        explode: false
        in: path
        name: routingNumber
        required: true
        schema:
          example: "987654320"
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileTransferConfig'
        required: true
      responses:
        200:
          description: Updated file transfer config
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Update file transfer config for a given routing number
      tags:
      - Admin
  /configs/filetransfers/cutoff-times/{routingNumber}:
    delete:
      operationId: deleteCutoffTime
      parameters:
      - description: Routing Number
        explode: false
        in: path
        name: routingNumber
        required: true
        schema:
          example: "987654320"
          type: string
        style: simple
      responses:
        200:
          description: Removed cutoff time
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Remove cutoff times for a given routing number
      tags:
      - Admin
    put:
      operationId: updateCutoffTime
      parameters:
      - description: Routing Number
        explode: false
        in: path
        name: routingNumber
        required: true
        schema:
          example: "987654320"
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CutoffTime'
        required: true
      responses:
        200:
          description: Updated cutoff time
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Update cutoff times for a given routing number
      tags:
      - Admin
  /configs/filetransfers/ftp/{routingNumber}:
    delete:
      operationId: deleteFTPConfig
      parameters:
      - description: Routing Number
        explode: false
        in: path
        name: routingNumber
        required: true
        schema:
          example: "987654320"
          type: string
        style: simple
      responses:
        200:
          description: Removed FTP config
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Remove FTP config for a given routing number
      tags:
      - Admin
    put:
      operationId: updateFTPConfig
      parameters:
      - description: Routing Number
        explode: false
        in: path
        name: routingNumber
        required: true
        schema:
          example: "987654320"
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FTPConfig'
        required: true
      responses:
        200:
          description: Updated FTP config
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Update FTP config for a given routing number
      tags:
      - Admin
  /configs/filetransfers/sftp/{routingNumber}:
    delete:
      operationId: deleteSFTPConfig
      parameters:
      - description: Routing Number
        explode: false
        in: path
        name: routingNumber
        required: true
        schema:
          example: "987654320"
          type: string
        style: simple
      responses:
        200:
          description: Removed SFTP config
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Remove SFTP config for a given routing number
      tags:
      - Admin
    put:
      operationId: updateSFTPConfig
      parameters:
      - description: Routing Number
        explode: false
        in: path
        name: routingNumber
        required: true
        schema:
          example: "987654320"
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SFTPConfig'
        required: true
      responses:
        200:
          description: Updated SFTP config
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Update SFTP config for a given routing number
      tags:
      - Admin
  /depositories/{depositoryId}/micro-deposits:
    get:
      operationId: getMicroDeposits
      parameters:
      - description: Depository ID
        explode: false
        in: path
        name: depositoryId
        required: true
        schema:
          example: e0d54e15
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/MicroDepositAmount'
                type: array
          description: Micro-deposit amounts posted to the given Depository
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Get micro-deposits for a Depository
      tags:
      - Admin
  /files/flush/incoming:
    post:
      operationId: flushIncomingFiles
      parameters:
      - description: Block HTTP response until all files are processed
        explode: true
        in: query
        name: wait
        required: true
        schema:
          example: true
          type: boolean
        style: form
      responses:
        200:
          description: All incoming files processed
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Download and process all incoming ACH files
      tags:
      - Admin
  /files/flush/outgoing:
    post:
      operationId: flushOutgoingFiles
      parameters:
      - description: Block HTTP response until all files are processed
        explode: true
        in: query
        name: wait
        required: true
        schema:
          example: true
          type: boolean
        style: form
      responses:
        200:
          description: All outgoing files processed
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Download and process all outgoing ACH files
      tags:
      - Admin
  /files/flush:
    post:
      operationId: flushFiles
      parameters:
      - description: Block HTTP response until all files are processed
        explode: true
        in: query
        name: wait
        required: true
        schema:
          example: true
          type: boolean
        style: form
      responses:
        200:
          description: All incoming and outgoing files processed
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Download and process all incoming and outgoing ACH files
      tags:
      - Admin
  /users/{userId}/depositories/{depositoryId}:
    put:
      operationId: updateDepositoryStatus
      parameters:
      - description: Moov User ID
        explode: false
        in: path
        name: userId
        required: true
        schema:
          example: e0d54e15
          type: string
        style: simple
      - description: Depository ID
        explode: false
        in: path
        name: depositoryId
        required: true
        schema:
          example: e0d54e15
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDepository'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Depository'
          description: Updated Depository config
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Update Depository status
      tags:
      - Admin
  /users/{userId}/transfers/{transferId}/status:
    put:
      operationId: updateTransferStatus
      parameters:
      - description: Moov User ID
        explode: false
        in: path
        name: userId
        required: true
        schema:
          example: e0d54e15
          type: string
        style: simple
      - description: Transfer ID
        explode: false
        in: path
        name: transferId
        required: true
        schema:
          example: e0d54e15
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTransferStatus'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
          description: Transfer with updated status
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Update a Transfer status
      tags:
      - Admin
components:
  schemas:
    Features:
      example:
        customersCallsDisabled: false
        accountsCallsDisabled: false
      properties:
        accountsCallsDisabled:
          default: false
          description: HTTP calls to Moov Accounts service are disabled
          type: boolean
        customersCallsDisabled:
          default: false
          description: HTTP calls to Moov Customers service are disabled
          type: boolean
    Configs:
      example:
        CutoffTimes:
        - location: America/New_York
          cutoff: 1700
        - location: America/New_York
          cutoff: 1700
        FileTransferConfigs:
        - returnPath: /ach/return/
          allowedIPs: 10.2.0.0/24
          inboundPath: /ach/inbound/
          outboundPath: /ach/outbound/
          outboundFilenameTemplate: |
            {{ date "20060102" }}-{{ .RoutingNumber }}-{{ .N }}.ach{{ if .GPG }}.gpg{{ end }}
        - returnPath: /ach/return/
          allowedIPs: 10.2.0.0/24
          inboundPath: /ach/inbound/
          outboundPath: /ach/outbound/
          outboundFilenameTemplate: |
            {{ date "20060102" }}-{{ .RoutingNumber }}-{{ .N }}.ach{{ if .GPG }}.gpg{{ end }}
        SFTPConfigs:
        - hostname: sftp.bank.com
          password: super-secret
          hostPublicKey: hostPublicKey
          username: paygate
          clientPrivateKey: clientPrivateKey
        - hostname: sftp.bank.com
          password: super-secret
          hostPublicKey: hostPublicKey
          username: paygate
          clientPrivateKey: clientPrivateKey
        FTPConfigs:
        - hostname: ftp.bank.com
          password: super-secret
          username: paygate
        - hostname: ftp.bank.com
          password: super-secret
          username: paygate
      properties:
        CutoffTimes:
          items:
            $ref: '#/components/schemas/CutoffTime'
          type: array
        FileTransferConfigs:
          items:
            $ref: '#/components/schemas/FileTransferConfig'
          type: array
        FTPConfigs:
          items:
            $ref: '#/components/schemas/FTPConfig'
          type: array
        SFTPConfigs:
          items:
            $ref: '#/components/schemas/SFTPConfig'
          type: array
    CutoffTime:
      example:
        location: America/New_York
        cutoff: 1700
      properties:
        cutoff:
          description: 24-hour timestamp for last processing minute
          example: 1700
          type: number
        location:
          description: IANA timezone name for cutoff time
          example: America/New_York
          type: string
      required:
      - cutoff
      - location
    FileTransferConfig:
      example:
        returnPath: /ach/return/
        allowedIPs: 10.2.0.0/24
        inboundPath: /ach/inbound/
        outboundPath: /ach/outbound/
        outboundFilenameTemplate: |
          {{ date "20060102" }}-{{ .RoutingNumber }}-{{ .N }}.ach{{ if .GPG }}.gpg{{ end }}
      properties:
        inboundPath:
          description: Filepath for inbound files
          example: /ach/inbound/
          type: string
        outboundPath:
          description: Filepath for outbound files
          example: /ach/outbound/
          type: string
        returnPath:
          description: Filepath for return files
          example: /ach/return/
          type: string
        outboundFilenameTemplate:
          description: |
            Go template for uploaded ACH filenames. Refer to our documentation on filename templates for more details.
            https://docs.moov.io/paygate/ach/#filename-templates
          example: |
            {{ date "20060102" }}-{{ .RoutingNumber }}-{{ .N }}.ach{{ if .GPG }}.gpg{{ end }}
          type: string
        allowedIPs:
          description: CIDR range or IP address for allowed remote server
          example: 10.2.0.0/24
          type: string
    FTPConfig:
      example:
        hostname: ftp.bank.com
        password: super-secret
        username: paygate
      properties:
        hostname:
          description: DNS or IP address for FTP server
          example: ftp.bank.com
          type: string
        username:
          description: username for authentication
          example: paygate
          type: string
        password:
          description: password for authentication
          example: super-secret
          type: string
      required:
      - hostname
      - username
    SFTPConfig:
      example:
        hostname: sftp.bank.com
        password: super-secret
        hostPublicKey: hostPublicKey
        username: paygate
        clientPrivateKey: clientPrivateKey
      properties:
        hostname:
          description: DNS or IP address for SFTP server
          example: sftp.bank.com
          type: string
        username:
          description: username for authentication
          example: paygate
          type: string
        password:
          description: password for authentication
          example: super-secret
          type: string
        clientPrivateKey:
          description: Base64 encoded string of SSH private key used for authentication
          type: string
        hostPublicKey:
          description: Base64 encoded string of SSH public key used to verify remote
            server
          type: string
      required:
      - hostname
      - username
    UpdateDepository:
      example: {}
      properties:
        status:
          $ref: '#/components/schemas/DepositoryStatus'
    UpdateTransferStatus:
      example: {}
      properties:
        status:
          $ref: '#/components/schemas/TransferStatus'
    MicroDepositAmount:
      description: A string with currency code and amount
      example:
        amount: '["USD 0.02","USD 0.06"]'
      properties:
        amount:
          example: '["USD 0.02","USD 0.06"]'
          type: string
    Error:
      properties:
        error:
          description: An error message describing the problem intended for humans.
          example: Validation error(s) present.
          type: string
      required:
      - error
    Depository:
      example:
        routingNumber: "051504597"
        metadata: Payroll
        created: 2000-01-23T04:56:07.000+00:00
        bankName: MVB Bank, Inc.
        holder: My Company,llc or Wade Arnold
        returnCodes:
        - reason: Account Closed
          code: R02
          description: Previously active account has been closed by customer or RDFI
        - reason: Account Closed
          code: R02
          description: Previously active account has been closed by customer or RDFI
        ID: 0c5e215c
        type: checking
        accountNumber: "0001027028"
        updated: 2000-01-23T04:56:07.000+00:00
        holderType: individual
      properties:
        ID:
          description: Depository ID
          example: 0c5e215c
          type: string
        bankName:
          description: Legal name of the financial institution.
          example: MVB Bank, Inc.
          type: string
        holder:
          description: Legal holder name on the account
          example: My Company,llc or Wade Arnold
          type: string
        holderType:
          description: Defines the type of entity of the account holder as an *individual*
            or *company*
          enum:
          - individual
          - company
          type: string
        type:
          description: Defines the account as *checking* or *savings*
          enum:
          - Checking
          - Savings
          example: checking
          type: string
        routingNumber:
          description: The ABA routing transit number for the depository account.
          example: "051504597"
          type: string
        accountNumber:
          description: The account number for the depository account
          example: "0001027028"
          type: string
        status:
          $ref: '#/components/schemas/DepositoryStatus'
        metadata:
          description: Additional meta data to be used for display only
          example: Payroll
          type: string
        returnCodes:
          items:
            $ref: '#/components/schemas/ReturnCode'
          type: array
        created:
          format: date-time
          type: string
        updated:
          format: date-time
          type: string
      required:
      - accountNumber
      - holder
      - holderType
      - routingNumber
      - type
    DepositoryStatus:
      description: Defines the status of the Depository account
      enum:
      - unverified
      - verified
      - rejected
      type: string
    ReturnCode:
      example:
        reason: Account Closed
        code: R02
        description: Previously active account has been closed by customer or RDFI
      properties:
        code:
          description: Optional NACHA return code for this Transfer
          example: R02
          type: string
        reason:
          description: Short NACHA description of return code
          example: Account Closed
          type: string
        description:
          description: Long form explanation of return code
          example: Previously active account has been closed by customer or RDFI
          type: string
    Transfer:
      example:
        amount: USD 99.99
        TELDetail:
          phoneNumber: 123.456.7890
          paymentType: single
        originatorDepository: 59276ce4
        receiver: feb492e6
        created: 2000-01-23T04:56:07.000+00:00
        IATDetail:
          ODFIBranchCurrencyCode: USD
          originatorState: PA
          originatorName: Jane Doe
          originatorAddress: 123 1st St
          ODFIName: My Bank
          RDFIName: Their Bank
          receiverCountryCode: GB
          receiverName: John Doe
          originatorCity: Anytown
          foreignCorrespondentBankBranchCountryCode: GB
          receiverCity: Othertown
          RDFIIDNumberQualifier: "01"
          foreignCorrespondentBankIDNumber: "631551"
          receiverAddress: 321 2nd St
          RDFIIdentification: "4"
          receiverPostalCode: "54321"
          originatorPostalCode: "12345"
          originatorCountryCode: US
          receiverState: GB
          foreignCorrespondentBankName: Their Bank
          RDFIBranchCurrencyCode: GB
          ODFIIdentification: "141451"
          foreignCorrespondentBankIDNumberQualifier: "5125112"
          ODFIIDNumberQualifier: "01"
        description: Loan Pay
        originator: 724b6abe
        returnCode:
          reason: Account Closed
          code: R02
          description: Previously active account has been closed by customer or RDFI
        receiverDepository: dad7ddfb
        standardEntryClassCode: WEB
        sameDay: false
        WEBDetail:
          paymentInformation: test payment
          paymentType: single
        transferType: push
        ID: 33164ac6
        CCDDetail:
          paymentInformation: test payment
      properties:
        ID:
          description: Optional ID to uniquely identify this transfer. If omitted,
            one will be generated
          example: 33164ac6
          type: string
        transferType:
          description: Type of transaction being actioned against the receiving institution.
            Expected values are pull (debits) or push (credits). Only one period used
            to signify decimal value will be included.
          enum:
          - push
          - pull
          example: push
          type: string
        amount:
          description: Amount of money. USD - United States.
          example: USD 99.99
          format: currency
          type: string
        originator:
          description: ID of the Originator account initiating the transfer.
          example: 724b6abe
          type: string
        originatorDepository:
          description: ID of the Originator Depository to be be used to override the
            default depository.
          example: 59276ce4
          type: string
        receiver:
          description: ID of the Receiver account the transfer was sent to.
          example: feb492e6
          type: string
        receiverDepository:
          description: ID of the Receiver Depository to be used to override the default
            depository
          example: dad7ddfb
          type: string
        description:
          description: Brief description of the transaction, that may appear on the
            receiving entityâ€™s financial statement
          example: Loan Pay
          maxLength: 79
          minLength: 1
          type: string
        standardEntryClassCode:
          description: Standard Entry Class code will be generated based on Receiver
            type for CCD and PPD
          example: WEB
          type: string
        status:
          $ref: '#/components/schemas/TransferStatus'
        sameDay:
          default: false
          description: When set to true this indicates the transfer should be processed
            the same day if possible.
          type: boolean
        returnCode:
          $ref: '#/components/schemas/ReturnCode'
        created:
          format: date-time
          type: string
        CCDDetail:
          $ref: '#/components/schemas/CCDDetail'
        IATDetail:
          $ref: '#/components/schemas/IATDetail'
        TELDetail:
          $ref: '#/components/schemas/TELDetail'
        WEBDetail:
          $ref: '#/components/schemas/WEBDetail'
      required:
      - amount
      - description
      - originator
      - receiver
      - type
    TransferStatus:
      description: Defines the state of the Transfer
      enum:
      - canceled
      - failed
      - reviewable
      - pending
      - processed
      - reclaimed
      type: string
    CCDDetail:
      example:
        paymentInformation: test payment
      properties:
        paymentInformation:
          description: Metadata for the transaction, placed in addenda 05 record
          example: test payment
          type: string
      required:
      - paymentInformation
    IATDetail:
      example:
        ODFIBranchCurrencyCode: USD
        originatorState: PA
        originatorName: Jane Doe
        originatorAddress: 123 1st St
        ODFIName: My Bank
        RDFIName: Their Bank
        receiverCountryCode: GB
        receiverName: John Doe
        originatorCity: Anytown
        foreignCorrespondentBankBranchCountryCode: GB
        receiverCity: Othertown
        RDFIIDNumberQualifier: "01"
        foreignCorrespondentBankIDNumber: "631551"
        receiverAddress: 321 2nd St
        RDFIIdentification: "4"
        receiverPostalCode: "54321"
        originatorPostalCode: "12345"
        originatorCountryCode: US
        receiverState: GB
        foreignCorrespondentBankName: Their Bank
        RDFIBranchCurrencyCode: GB
        ODFIIdentification: "141451"
        foreignCorrespondentBankIDNumberQualifier: "5125112"
        ODFIIDNumberQualifier: "01"
      properties:
        originatorName:
          description: Name of originating entity
          example: Jane Doe
          type: string
        originatorAddress:
          description: Address of originating entity
          example: 123 1st St
          type: string
        originatorCity:
          description: City of originating entity
          example: Anytown
          type: string
        originatorState:
          description: State of originating entity
          example: PA
          type: string
        originatorPostalCode:
          description: Postal code of originating entity
          example: "12345"
          type: string
        originatorCountryCode:
          description: ISO 3166 Country code of originating entity
          example: US
          type: string
        ODFIName:
          description: Name of originating financial institution
          example: My Bank
          type: string
        ODFIIDNumberQualifier:
          description: ID qualifier number of originating FI
          example: "01"
          type: string
        ODFIIdentification:
          description: Identification of originating FI
          example: "141451"
          type: string
        ODFIBranchCurrencyCode:
          description: ISO 4217 currency code of originating entity
          example: USD
          type: string
        receiverName:
          description: Name of receiving entity
          example: John Doe
          type: string
        receiverAddress:
          description: Address of originating entity
          example: 321 2nd St
          type: string
        receiverCity:
          description: City of originating entity
          example: Othertown
          type: string
        receiverState:
          description: State of originating entity
          example: GB
          type: string
        receiverPostalCode:
          description: Postal code of originating entity
          example: "54321"
          type: string
        receiverCountryCode:
          description: ISO 3166 country code of originating entity
          example: GB
          type: string
        RDFIName:
          description: Name of receiving financial institution
          example: Their Bank
          type: string
        RDFIIDNumberQualifier:
          description: ID qualifier number of originating FI
          example: "01"
          type: string
        RDFIIdentification:
          description: Identification of receiving financial institution
          example: "4"
          type: string
        RDFIBranchCurrencyCode:
          description: ISO 4217 currency code of receiving entity
          example: GB
          type: string
        foreignCorrespondentBankName:
          description: Name of foreign bank used in IAT transfer
          example: Their Bank
          type: string
        foreignCorrespondentBankIDNumberQualifier:
          description: ID qualifier of foreign bank used
          example: "5125112"
          type: string
        foreignCorrespondentBankIDNumber:
          description: ID number of foreign bank used
          example: "631551"
          type: string
        foreignCorrespondentBankBranchCountryCode:
          description: ISO 3166 country code of foreign bank used
          example: GB
          type: string
    TELDetail:
      example:
        phoneNumber: 123.456.7890
        paymentType: single
      properties:
        phoneNumber:
          description: Phone number for optional communication during business hours
            required for TEL transfers
          example: 123.456.7890
          type: string
        paymentType:
          description: Defines if the transfer is authorized for a single transaction
            or reoccurring
          enum:
          - single
          - reoccurring
          example: single
          type: string
    WEBDetail:
      example:
        paymentInformation: test payment
        paymentType: single
      properties:
        paymentInformation:
          description: Metadata for the transaction, placed in addenda 05 record
          example: test payment
          type: string
        paymentType:
          description: Defines if the transfer is authorized for a single transaction
            or reoccurring
          enum:
          - single
          - reoccurring
          example: single
          type: string
